use_frameworks!

target 'MyLibrary_Example' do
  pod 'MyLibrary', :path => '../'

  target 'MyLibrary_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
